# Generated by Django 4.2.7 on 2023-12-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('images', models.ImageField(upload_to='files/posts/images/%y/%m/%d')),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
    ]
