# Generated by Django 4.2.7 on 2023-12-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='files/posts/images/%y/%m/%d'),
        ),
    ]
